# This is a basic workflow to help you get started with Actions

name: Run Test Suite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Run Testsuite
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
          - name: Run Test
            uses: convictional/trigger-workflow-and-wait@v1.3.0
            with: 
              owner: AswathN
              repo: my-App
              github_token: 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
              workflow_file_name: AppTest.yml
    # Runs a single command using the runners shell
          - name: deploy
            run: |
              echo "test suite"
